spring:
    datasource:
        url: jdbc:mysql://test-yansou.mysql.rds.aliyuncs.com:3306/test-ruangong?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8&useSSL=true
        username: cim
        password: yansou2016+
        tomcat:
            max-wait: 10000
            max-idle: 50
            max-active: 50
            test-on-borrow: true
            test-while-idle: true

    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: false
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

    #freemarker
    freemarker:
        request-context-attribute: request  #req访问request
        cache: false
        charset: UTF-8
        settings:
            number_format: 0.##   #数字格式化，无小数点
#        prefix: classpath:/templates/
#        suffix: .ftl

#    mvc:
#        static-path-pattern: /css/**,/js/**
#    resources:
#        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/

server:
    port: 8080



